name = "square-worker"
main = "./cloudflare/worker.js"
compatibility_date = "2024-12-18"

[vars]
ENVIRONMENT = "sandbox"

[env.sandbox]
vars = { ENVIRONMENT = "sandbox" }

[env.production]
vars = { ENVIRONMENT = "production" }
