name = "square-worker"
main = "./cloudflare/worker.js"
compatibility_date = "2024-12-18"

[vars]
ENVIRONMENT = "sandbox"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
