name = "square-worker" # Primary worker for handling Square requests
main = "./cloudflare/square-worker.js" # Entry point for the Square worker
compatibility_date = "2024-12-18"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[kv_namespaces]]
binding = "IDEMPOTENCY_STORE"
id = "2d9bdc1c576442aabe941b6cfb99ab6e"
preview_id = "6ba2be1c3b854ec3bd6726874bfd49b7"

[[kv_namespaces]]
binding = "CATALOG_JSON"
id = "55b77bbd70ba49c6b3bc11e7bee26afc"
preview_id = "3ab1a17c4be44dc4a348ae2846866dbf"
